alter table book_order drop foreign key FKg9dfl5a6p0v1s3infwn0njds9;
alter table inventory drop foreign key FK8rus8qhfxl7ds6cv9xtawtrrk;
alter table line drop foreign key FKrfb31phil3f8eiqyayoukux8f;
alter table line drop foreign key FKc6jmkmvtqi6ge9in0umab27yi;
drop table if exists book;
drop table if exists BOOK_ID_SEQ;
drop table if exists book_order;
drop table if exists BOOKORDER_ID_SEQ;
drop table if exists customer;
drop table if exists CUSTOMER_ID_SEQ;
drop table if exists inventory;
drop table if exists INVENTORY_ID_SEQ;
drop table if exists line;
drop table if exists ORDERLINE_ID_SEQ;
create table book (bookId bigint not null, isbn varchar(255), price float not null, title varchar(500), primary key (bookId)) engine=InnoDB;
create table BOOK_ID_SEQ (next_val bigint) engine=InnoDB;
insert into BOOK_ID_SEQ values ( 1 );
create table book_order (orderId bigint not null, createdAt datetime, isFulfilled char(1), orderTotal float not null, customer_id bigint not null, primary key (orderId)) engine=InnoDB;
create table BOOKORDER_ID_SEQ (next_val bigint) engine=InnoDB;
insert into BOOKORDER_ID_SEQ values ( 1 );
create table customer (customerId bigint not null, address varchar(500), email varchar(50), name varchar(255), primary key (customerId)) engine=InnoDB;
create table CUSTOMER_ID_SEQ (next_val bigint) engine=InnoDB;
insert into CUSTOMER_ID_SEQ values ( 1 );
create table inventory (inventoryId bigint not null, noOfCopies integer, book_id bigint not null, primary key (inventoryId)) engine=InnoDB;
create table INVENTORY_ID_SEQ (next_val bigint) engine=InnoDB;
insert into INVENTORY_ID_SEQ values ( 1 );
create table line (orderLineId bigint not null, itemTotal float, quantity integer, book_id bigint not null, order_id bigint not null, primary key (orderLineId)) engine=InnoDB;
create table ORDERLINE_ID_SEQ (next_val bigint) engine=InnoDB;
insert into ORDERLINE_ID_SEQ values ( 1 );
alter table book_order add constraint FKg9dfl5a6p0v1s3infwn0njds9 foreign key (customer_id) references customer (customerId);
alter table inventory add constraint FK8rus8qhfxl7ds6cv9xtawtrrk foreign key (book_id) references book (bookId);
alter table line add constraint FKrfb31phil3f8eiqyayoukux8f foreign key (book_id) references book (bookId);
alter table line add constraint FKc6jmkmvtqi6ge9in0umab27yi foreign key (order_id) references book_order (orderId);
