alter table review drop foreign key FKtrw4aj9s48xdyu198mco3ngwg;
drop table if exists listing;
drop table if exists LISTING_ID_SEQ;
drop table if exists review;
drop table if exists REVIEW_ID_SEQ;
create table listing (listingId bigint not null, accomodates integer not null, amenities varchar(255), bathrooms integer not null, beds integer not null, cancellationPolicy varchar(255), city varchar(255), description varchar(255), hostname varchar(255), name varchar(255), pictureUrl varchar(255), price float not null, reviewScoreRating float not null, state varchar(255), primary key (listingId)) engine=InnoDB;
create table LISTING_ID_SEQ (next_val bigint) engine=InnoDB;
insert into LISTING_ID_SEQ values ( 1 );
create table review (reviewerId bigint not null, comments varchar(255), listing_id bigint not null, primary key (reviewerId)) engine=InnoDB;
create table REVIEW_ID_SEQ (next_val bigint) engine=InnoDB;
insert into REVIEW_ID_SEQ values ( 1 );
alter table review add constraint FKtrw4aj9s48xdyu198mco3ngwg foreign key (listing_id) references listing (listingId);
